mod lua;

pub use lua::{Action, Keybind, LuaConfig, LuaState, RuleActions, WindowMatch, WindowRule};

#[derive(Debug, Clone)]
pub struct Config {
    pub border_width: u32,
    pub border_color_focused: u32,
    pub border_color_unfocused: u32,
    pub border_color_urgent: u32,
    pub gap_inner: u32,
    pub gap_outer: u32,
    // Title bar settings
    pub titlebar_enabled: bool,
    pub titlebar_height: u32,
    pub titlebar_color_focused: u32,
    pub titlebar_color_unfocused: u32,
    pub titlebar_text_color: u32,
    // Behavior settings
    pub follow_window_on_move: bool,
    pub mouse_follows_focus: bool,
    // Manual bar/panel reserved space (overrides struts)
    pub bar_height: u32,
    // Compositor visual settings (picom)
    // These are stored for reference and potential dynamic picom config generation
    pub corner_radius: u32,
    pub blur_enabled: bool,
    pub blur_method: String,
    pub blur_strength: u32,
    pub shadow_enabled: bool,
    pub shadow_radius: u32,
    pub shadow_opacity: f64,
    pub shadow_offset_x: i32,
    pub shadow_offset_y: i32,
    pub opacity_focused: f64,
    pub opacity_unfocused: f64,
    pub fade_enabled: bool,
    pub fade_delta: u32,
}

impl Config {
    /// Generate picom.conf content from current config settings.
    pub fn generate_picom_config(&self) -> String {
        let blur_section = if self.blur_enabled {
            format!(
                r#"# Blur
blur-method = "{}";
blur-strength = {};
blur-background = true;
blur-background-frame = false;
blur-kern = "3x3box";

blur-background-exclude = [
    "window_type = 'dock'",
    "window_type = 'desktop'",
    "window_type = 'menu'",
    "window_type = 'dropdown_menu'",
    "window_type = 'popup_menu'",
    "_NET_WM_BYPASS_COMPOSITOR@:32c = 1"
];"#,
                self.blur_method, self.blur_strength
            )
        } else {
            "# Blur disabled".to_string()
        };

        let shadow_section = if self.shadow_enabled {
            format!(
                r#"# Shadows
shadow = true;
shadow-radius = {};
shadow-opacity = {:.2};
shadow-offset-x = {};
shadow-offset-y = {};

shadow-exclude = [
    "window_type = 'dock'",
    "window_type = 'desktop'",
    "window_type = 'menu'",
    "window_type = 'dropdown_menu'",
    "window_type = 'popup_menu'",
    "window_type = 'tooltip'",
    "_NET_WM_STATE@:32a *= '_NET_WM_STATE_FULLSCREEN'",
    "_NET_WM_BYPASS_COMPOSITOR@:32c = 1"
];"#,
                self.shadow_radius,
                self.shadow_opacity,
                self.shadow_offset_x,
                self.shadow_offset_y
            )
        } else {
            "# Shadows disabled\nshadow = false;".to_string()
        };

        let fade_section = if self.fade_enabled {
            format!(
                r#"# Fading / Animations
fading = true;
fade-in-step = 0.028;
fade-out-step = 0.03;
fade-delta = {};

no-fading-destroyed-argb = true;

fade-exclude = [
    "window_type = 'menu'",
    "window_type = 'dropdown_menu'",
    "window_type = 'popup_menu'"
];"#,
                self.fade_delta
            )
        } else {
            "# Fading disabled\nfading = false;".to_string()
        };

        let opacity_section = if self.opacity_unfocused < 1.0 {
            format!(
                r#"# Focus Opacity
active-opacity = {:.2};
inactive-opacity = {:.2};
frame-opacity = 1.0;"#,
                self.opacity_focused, self.opacity_unfocused
            )
        } else {
            "# Focus opacity: all windows fully opaque".to_string()
        };

        format!(
            r#"# picom.conf - Auto-generated by gar window manager
# DO NOT EDIT MANUALLY - changes will be overwritten on reload
# Edit ~/.config/gar/init.lua instead and reload with Mod+Shift+R

# Backend Configuration
backend = "glx";
vsync = true;
use-ewmh-active-win = true;
glx-no-stencil = true;
glx-no-rebind-pixmap = true;

# Rounded Corners
corner-radius = {};

rounded-corners-exclude = [
    "window_type = 'dock'",
    "window_type = 'desktop'",
    "window_type = 'tooltip'",
    "window_type = 'menu'",
    "window_type = 'dropdown_menu'",
    "window_type = 'popup_menu'",
    "_NET_WM_STATE@:32a *= '_NET_WM_STATE_FULLSCREEN'"
];

{}

{}

{}

{}

# Window Type Settings
wintypes:
{{
    tooltip = {{
        fade = true;
        shadow = false;
        opacity = 0.95;
        focus = true;
        blur-background = false;
    }};
    dock = {{
        shadow = false;
        clip-shadow-above = true;
    }};
    dnd = {{
        shadow = false;
    }};
    popup_menu = {{
        opacity = 0.95;
        shadow = false;
    }};
    dropdown_menu = {{
        opacity = 0.95;
        shadow = false;
    }};
}};
"#,
            self.corner_radius,
            blur_section,
            shadow_section,
            fade_section,
            opacity_section
        )
    }

    /// Write picom config to ~/.config/gar/picom.conf and signal picom to reload.
    pub fn write_picom_config(&self) -> std::io::Result<()> {
        let config_dir = dirs::config_dir()
            .ok_or_else(|| std::io::Error::new(
                std::io::ErrorKind::NotFound,
                "Could not determine config directory"
            ))?
            .join("gar");

        // Ensure directory exists
        std::fs::create_dir_all(&config_dir)?;

        let config_path = config_dir.join("picom.conf");
        let content = self.generate_picom_config();

        std::fs::write(&config_path, &content)?;
        tracing::info!("Generated picom config at {:?}", config_path);

        // Signal picom to reload
        Self::reload_picom();

        Ok(())
    }

    /// Restart picom to apply new configuration.
    /// Picom doesn't support config reload via signal, so we kill and restart it.
    fn reload_picom() {
        use std::process::Command;
        use std::thread;
        use std::time::Duration;

        // Kill existing picom
        match Command::new("pkill").arg("picom").status() {
            Ok(status) if status.success() => {
                tracing::info!("Killed picom for restart");
            }
            Ok(_) => {
                tracing::debug!("picom was not running");
            }
            Err(e) => {
                tracing::warn!("Failed to kill picom: {}", e);
                return;
            }
        }

        // Brief pause to let picom fully exit
        thread::sleep(Duration::from_millis(100));

        // Restart picom with the new config
        let config_path = dirs::config_dir()
            .map(|d| d.join("gar").join("picom.conf"))
            .unwrap_or_default();

        match Command::new("picom")
            .args(["-b", "--config"])
            .arg(&config_path)
            .spawn()
        {
            Ok(_) => {
                tracing::info!("Restarted picom with config {:?}", config_path);
            }
            Err(e) => {
                tracing::warn!("Failed to restart picom: {}", e);
            }
        }
    }
}

impl Default for Config {
    fn default() -> Self {
        Self {
            border_width: 2,
            border_color_focused: 0x5294e2,
            border_color_unfocused: 0x2d2d2d,
            border_color_urgent: 0xff5555, // Red for urgent windows
            gap_inner: 0,
            gap_outer: 0,
            // Title bars disabled by default
            titlebar_enabled: false,
            titlebar_height: 20,
            titlebar_color_focused: 0x3d3d3d,
            titlebar_color_unfocused: 0x2d2d2d,
            titlebar_text_color: 0xffffff,
            // Behavior: follow window when moving to another workspace
            follow_window_on_move: false,
            // Behavior: warp mouse pointer to center of focused window
            mouse_follows_focus: false,
            // Manual bar height (0 = use struts from dock windows)
            bar_height: 0,
            // Compositor settings (picom) - matching picom.conf defaults
            corner_radius: 12,
            blur_enabled: true,
            blur_method: "dual_kawase".to_string(),
            blur_strength: 5,
            shadow_enabled: true,
            shadow_radius: 12,
            shadow_opacity: 0.75,
            shadow_offset_x: -7,
            shadow_offset_y: -7,
            opacity_focused: 1.0,
            opacity_unfocused: 1.0, // No unfocused dimming by default
            fade_enabled: true,
            fade_delta: 10,
        }
    }
}
